"use client";
import AppShell from "@/components/AppShell";
import {api,apiBlob} from "@/lib/api";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect,useMemo,useState} from "react";

type Scenario={id:string;moduleName?:string;featureName?:string;name:string;status:string;currentVersion:number;createdAt:string};
type RunResult={scenarioId:string;scenarioName:string;status:string;exitCode?:number;durationMs:number;stdout:string;stderr:string};
type RunResponse={total:number;passed:number;failed:number;results:RunResult[]};

export default function ScenarioRepository(){
 const {workspaceId,applicationId}=useParams<{workspaceId:string;applicationId:string}>();
 const [items,setItems]=useState<Scenario[]>([]);const [selected,setSelected]=useState<Set<string>>(new Set());const [target,setTarget]=useState("PLAYWRIGHT_PYTEST");
 const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState("");const [runResults,setRunResults]=useState<Record<string,RunResult>>({});
 async function load(){try{setError("");setItems(await api<Scenario[]>(`/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenarios`))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[workspaceId,applicationId]);
 const allSelected=items.length>0&&items.every(x=>selected.has(x.id));const selectedIds=useMemo(()=>Array.from(selected),[selected]);
 const locatorError=error.includes("UNSUPPORTED_LOCATOR")||error.includes("LOCATOR_REQUIRED");
 function toggle(id:string){setSelected(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n})}
 function toggleAll(){setSelected(allSelected?new Set():new Set(items.map(x=>x.id)))}
 async function exportSelected(){if(!selectedIds.length)return;try{setBusy("export");setError("");setMessage("");const blob=await apiBlob(`/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenario-actions/export`,{method:"POST",body:JSON.stringify({scenarioIds:selectedIds,target})});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`combined-automation-project-${target.toLowerCase()}.zip`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage(`Combined automation project created for ${selectedIds.length} selected scenario(s). Check bulk-manifest.json inside the ZIP for export status.`)}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function run(ids:string[],label:string){try{setBusy(label);setError("");setMessage("");const r=await api<RunResponse>(`/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenario-actions/run`,{method:"POST",body:JSON.stringify({scenarioIds:ids})});const map={...runResults};r.results.forEach(x=>map[x.scenarioId]=x);setRunResults(map);const firstProblem=r.results.find(x=>x.status!=="PASSED");if(firstProblem){setError(firstProblem.stderr||firstProblem.stdout||`${firstProblem.scenarioName}: ${firstProblem.status}`)}else{setMessage(`Run complete: ${r.passed} passed, ${r.failed} failed.`)}}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function deleteScenario(s:Scenario){if(!window.confirm(`Delete scenario "${s.name}" permanently? This will also remove its generated implementations.`))return;try{setBusy(`delete-${s.id}`);setError("");setMessage("");await api(`/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${s.id}`,{method:"DELETE"});setSelected(prev=>{const n=new Set(prev);n.delete(s.id);return n});setMessage(`Scenario "${s.name}" deleted.`);await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 return <AppShell><div className="breadcrumb"><Link href="/workspaces">Workspaces</Link><span>/</span><Link href={`/workspaces/${workspaceId}/applications/${applicationId}`}>Application</Link><span>/</span><span>Scenario repository</span></div><div className="hero"><div><h1>Scenario Repository</h1><p className="muted">List view for selecting, exporting and running one or many scenarios.</p></div><span className="badge">{items.length} scenarios</span></div>{error&&<div className="error">{locatorError?<><strong>Scenario cannot be generated or executed.</strong><div style={{marginTop:6}}>One or more recorded steps has no supported locator. Re-record the affected step after this v0.1.2 recorder update, then save the scenario again.</div><details style={{marginTop:8}}><summary>Technical details</summary><code>{error}</code></details></>:error}</div>}{message&&<div className="success" style={{marginBottom:12}}>{message}</div>}
 <section className="card scenario-toolbar"><div className="actions"><button className="secondary" onClick={toggleAll}>{allSelected?"Clear selection":"Select all"}</button><span className="badge">{selectedIds.length} selected</span><select value={target} onChange={e=>setTarget(e.target.value)} aria-label="Export framework"><option value="PLAYWRIGHT_PYTEST">Python + Playwright + Pytest</option><option value="SELENIUM_TESTNG">Java + Selenium + TestNG</option></select><button onClick={exportSelected} disabled={!selectedIds.length||busy==="export"}>{busy==="export"?"Exporting…":"Export selected"}</button><button onClick={()=>run(selectedIds,"run-bulk")} disabled={!selectedIds.length||busy==="run-bulk"}>{busy==="run-bulk"?"Running…":"Run selected"}</button></div><p className="muted small-note">Run uses the local Playwright runner and generates a fresh Playwright implementation from the canonical IR before execution.</p></section>
 {items.length===0?<div className="empty">No recorded scenarios yet. Return to an environment and click Record Test.</div>:<section className="card" style={{marginTop:14,overflowX:"auto"}}><table className="table scenario-table"><thead><tr><th><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Select all scenarios"/></th><th>Module</th><th>Feature</th><th>Scenario</th><th>Status</th><th>Version</th><th>Last run</th><th>Actions</th></tr></thead><tbody>{items.map(s=>{const rr=runResults[s.id];return <tr key={s.id}><td><input type="checkbox" checked={selected.has(s.id)} onChange={()=>toggle(s.id)} aria-label={`Select ${s.name}`}/></td><td>{s.moduleName||"—"}</td><td>{s.featureName||"—"}</td><td><Link className="table-link" href={`/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${s.id}`}>{s.name}</Link></td><td><span className="badge ok">{s.status}</span></td><td>v{s.currentVersion}</td><td>{rr?<span className={`badge ${rr.status==="PASSED"?"ok":rr.status==="FAILED"?"warn":""}`} title={(rr.stderr||rr.stdout).slice(0,500)}>{rr.status}</span>:"—"}</td><td><div className="actions scenario-row-actions"><Link className="button secondary compact" href={`/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${s.id}`}>View</Link><button className="compact" onClick={()=>run([s.id],`run-${s.id}`)} disabled={busy===`run-${s.id}`}>{busy===`run-${s.id}`?"Running…":"Run"}</button><button className="danger compact" onClick={()=>deleteScenario(s)} disabled={busy===`delete-${s.id}`}>{busy===`delete-${s.id}`?"Deleting…":"Delete"}</button></div></td></tr>})}</tbody></table></section>}
 </AppShell>
}
