"use client";
import AppShell from "@/components/AppShell";
import { api } from "@/lib/api";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Workspace={id:string;key:string;name:string;description?:string;status:string;role:string};
type Me={displayName:string;email:string};

export default function WorkspacesPage(){
 const [items,setItems]=useState<Workspace[]>([]);const [me,setMe]=useState<Me|null>(null);
 const [name,setName]=useState("");const [key,setKey]=useState("");const [description,setDescription]=useState("");
 const [editId,setEditId]=useState<string|null>(null);const [editName,setEditName]=useState("");const [editKey,setEditKey]=useState("");const [editDescription,setEditDescription]=useState("");
 const [busy,setBusy]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function load(){try{setError("");const [w,m]=await Promise.all([api<Workspace[]>("/api/v1/workspaces"),api<Me>("/api/v1/me")]);setItems(w);setMe(m)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();try{setBusy("create");setError("");await api<Workspace>("/api/v1/workspaces",{method:"POST",body:JSON.stringify({name,key,description})});setName("");setKey("");setDescription("");setMessage("Workspace created.");await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 function beginEdit(w:Workspace){setEditId(w.id);setEditName(w.name);setEditKey(w.key);setEditDescription(w.description??"");setMessage("");setError("")}
 async function saveEdit(w:Workspace){try{setBusy(`edit-${w.id}`);setError("");await api(`/api/v1/workspaces/${w.id}`,{method:"PUT",body:JSON.stringify({name:editName,key:editKey,description:editDescription})});setEditId(null);setMessage("Workspace updated.");await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 async function remove(w:Workspace){if(!window.confirm(`Remove workspace \"${w.name}\"? It will be hidden and access will be disabled. Existing database records are retained for audit/history.`))return;try{setBusy(`delete-${w.id}`);setError("");await api(`/api/v1/workspaces/${w.id}`,{method:"DELETE"});setMessage("Workspace removed.");await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}}
 return <AppShell><div className="hero"><div><h1>Workspaces</h1><p className="muted">Welcome {me?.displayName ?? ""}. Workspace is the authorization boundary for applications and test assets.</p></div></div>{error&&<div className="error">{error}</div>}{message&&<div className="success" style={{marginTop:10}}>{message}</div>}<div className="grid" style={{marginTop:16}}><section className="card"><h2>Create workspace</h2><form className="stack" onSubmit={create}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={200}/></label><label>Key<input value={key} onChange={e=>setKey(e.target.value)} required placeholder="SQA"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy==="create"}>{busy==="create"?"Creating…":"Create workspace"}</button></form></section><section className="card"><h2>Your workspaces</h2>{items.length===0?<div className="empty">No workspaces yet.</div>:<div className="stack">{items.map(w=><div className="workspace-item" key={w.id}>{editId===w.id?<div className="stack"><label>Name<input value={editName} onChange={e=>setEditName(e.target.value)} /></label><label>Key<input value={editKey} onChange={e=>setEditKey(e.target.value)} /></label><label>Description<textarea value={editDescription} onChange={e=>setEditDescription(e.target.value)} /></label><div className="actions"><button onClick={()=>saveEdit(w)} disabled={busy===`edit-${w.id}`}>{busy===`edit-${w.id}`?"Saving…":"Save"}</button><button className="secondary" onClick={()=>setEditId(null)}>Cancel</button></div></div>:<><div className="actions" style={{justifyContent:"space-between"}}><Link className="workspace-name" href={`/workspaces/${w.id}`}><strong>{w.name}</strong></Link><span className="badge">{w.role}</span></div><div className="muted">{w.key} · {w.status}</div>{w.description&&<p>{w.description}</p>}<div className="actions"><Link className="button" href={`/workspaces/${w.id}`}>Open</Link>{w.role==="ADMINISTRATOR"&&<><button className="secondary" onClick={()=>beginEdit(w)}>Edit</button><button className="danger" onClick={()=>remove(w)} disabled={busy===`delete-${w.id}`}>{busy===`delete-${w.id}`?"Removing…":"Remove"}</button></>}</div></>}</div>)}</div>}</section></div></AppShell>;
}
