"use client";
import AppShell from "@/components/AppShell";import {api} from "@/lib/api";import Link from "next/link";import {useParams} from "next/navigation";import {useEffect,useState} from "react";
type Detail={scenario:{id:string;moduleName?:string;featureName?:string;name:string;status:string;currentVersion:number};versionNo:number;sourceRecordingSessionId:string;automationIr:unknown;versionCreatedAt:string};
type Impl={id:string;targetProfile:string;implementationVersion:number;generatorVersion:string;status:string;sourceHash:string;createdAt:string};
export default function ScenarioDetail(){const {workspaceId,applicationId,scenarioId}=useParams<{workspaceId:string;applicationId:string;scenarioId:string}>();const [d,setD]=useState<Detail|null>(null);const [impls,setImpls]=useState<Impl[]>([]);const [target,setTarget]=useState("PLAYWRIGHT_PYTEST");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
async function load(){try{const [detail,list]=await Promise.all([api<Detail>(`/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${scenarioId}`),api<Impl[]>(`/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${scenarioId}/implementations`)]);setD(detail);setImpls(list)}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[workspaceId,applicationId,scenarioId]);
async function generate(){try{setBusy(true);setError("");setMessage("");await api(`/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${scenarioId}/implementations`,{method:"POST",body:JSON.stringify({target})});setMessage("Framework implementation generated from the current canonical IR.");await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <AppShell><div className="breadcrumb"><Link href={`/workspaces/${workspaceId}/applications/${applicationId}/scenarios`}>Scenario repository</Link><span>/</span><span>{d?.scenario.name??"Scenario"}</span></div>{error&&<div className="error">{error}</div>}{message&&<div className="success" style={{marginBottom:12}}>{message}</div>}{d&&<><div className="hero"><div><div className="scenario-path"><span>{d.scenario.moduleName||"Unassigned module"}</span><span>→</span><span>{d.scenario.featureName||"Unassigned feature"}</span></div><h1>{d.scenario.name}</h1><p className="muted">Source recording: {d.sourceRecordingSessionId}</p></div><div className="actions"><span className="badge ok">{d.scenario.status}</span><span className="badge">Scenario v{d.versionNo}</span><Link className="button secondary" href={`/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${scenarioId}/edit`}>Edit / save as new</Link></div></div>
<section className="card codegen-card"><div className="codegen-head"><div><h2>Framework-Neutral Code Generator</h2><p className="muted">Generate immutable framework implementations from this exact Automation IR. Generated code never becomes the Scenario source of truth.</p></div><div className="codegen-controls"><select value={target} onChange={e=>setTarget(e.target.value)}><option value="PLAYWRIGHT_PYTEST">Python + Playwright + Pytest</option><option value="SELENIUM_TESTNG">Java + Selenium + TestNG</option></select><button onClick={generate} disabled={busy}>{busy?"Generating…":"Generate Code"}</button></div></div>
{impls.length===0?<div className="empty">No generated implementations yet.</div>:<div className="implementation-grid">{impls.map(i=><div className="implementation-item" key={i.id}><div><strong>{i.targetProfile==="PLAYWRIGHT_PYTEST"?"Python · Playwright · Pytest":"Java · Selenium · TestNG"}</strong><div className="muted">Implementation v{i.implementationVersion} · Generator {i.generatorVersion}</div><code className="hash">{i.sourceHash.slice(0,16)}…</code></div><div className="actions"><span className="badge ok">{i.status}</span><Link className="button secondary" href={`/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${scenarioId}/implementations/${i.id}`}>View Code</Link><a className="button" href={`http://localhost:8080/api/v1/workspaces/${workspaceId}/applications/${applicationId}/scenarios/${scenarioId}/implementations/${i.id}/download`}>Download ZIP</a></div></div>)}</div>}</section>
<section className="card" style={{marginTop:16}}><h2>Canonical Automation IR</h2><p className="muted">Source of truth. Code Generator inputs are immutable Scenario Version + IR + target profile.</p><pre className="code-panel">{JSON.stringify(d.automationIr,null,2)}</pre></section></>}</AppShell>}
